openapi: 3.0.3
info:
  title: KB-Reader API
  description: |-
    This API is designed to return either the structure of the KB documentation in JSON format, or the markdown relevant to the
    requested content
  contact:
    email: ryan@reabelx.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /structure:
    get: 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Structure'
        '400':
          description: Invalid status value
  /markdown/{pageref}:
    get:
      tags:
        - markdown
      summary: Find purchase order by ID
      description: For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
      operationId: getOrderById
      parameters:
        - name: pageref
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:        
            text/plain:
              schema:
                type: string
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
components:
  schemas:
    Structure:
      required:
        - label
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        label:
          type: string
          example: React
        path:
          type: string
          example: Javascript/React
        SubItems:
          type: array
          items:
            $ref: '#/components/schemas/Structure'
  requestBodies:
    Structure:
      description: Markdown structure metadata
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Structure'
    Markdown:
      description: Pet object that needs to be added to the store
      content:            
        text/plain:
          schema:
            type: string