openapi: 3.1.0
info:
  title: deck-randomizer
  description: |-
    API to return a randomized collection of cards
  contact:
    email: ryan@reabelx.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /deal:
    get: 
      parameters:
        - name: suites
          in: body
          description: array of suites to be provided back, defaults to all when empty
          required: false
          schema:
            type: array
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Structure'
        '400':
          description: Invalid status value
components:
  schemas:
    Structure:
      required:
        - label
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        label:
          type: string
          example: React
        path:
          type: string
          example: Javascript/React
        SubItems:
          type: array
          items:
            $ref: '#/components/schemas/Structure'
  requestBodies:
    Structure:
      description: Markdown structure metadata
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Structure'
    Markdown:
      description: Pet object that needs to be added to the store
      content:            
        text/plain:
          schema:
            type: string